config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  
  delete '/logout' => 'sessions#destroy'

  get '/reviews/newest_reviews' => 'reviews#newest_reviews'

  get '/auth/:provider/callback' => 'sessions#omniauth'
  
  resources :reviews
  resources :animes do
    resources :reviews, only: [:new, :create, :index, ]
  end
  resources :users do 
    resources :reviews, only: [:index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
    has_many :reviews 
    has_many :users, through: :reviews
    validates :title, uniqueness: true, presence: true

    

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  validates :rating, :content, :anime, presence: true
  validates :anime, uniqueness: {scope: :user_id, message: "may only have one review per user, please just edit your existing one."}

  def self.newest_reviews
    self.order(:created_at).limit(5)
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :animes, through: :reviews

    validates :username, uniqueness: true, presence: true
    validates :password, presence:true 
    has_secure_password 
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new 
        @anime = Anime.new
    end

    def create
        @anime = Anime.new(anime_params)
        if @anime.save
            redirect_to animes_path
        else
            render :new
        end
    end

    def index
        @animes = Anime.all
    end

    def show 
        @anime = Anime.find_by_id(params[:id])
        redirect_to animes_path if !@anime
    end


    private 

    def anime_params
        params.require(:anime).permit(:title)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
###gives access to methods in views
    helper_method :current_user, :logged_in?

    private

        def current_user
            @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
        end

        def logged_in?
            !!session[:user_id]
        end

        def redirect_if_not_logged_in
            redirect_to '/' if !logged_in?
        end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_review, only: [:edit, :update]

    def index 
        if check_anime
            @reviews = @anime.reviews 
        elsif check_user
            @reviews = current_user.reviews
        else
            @reviews = Review.all 
        end

    end

    def new
        if check_anime
            @review = @anime.reviews.build
        else
            @review = Review.new 
        end
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to user_reviews_path(current_user)
        else 
            render :new 
        end
    end

    def edit
    end

    def update 
        if @review.update(review_params)
            redirect_to user_reviews_path(current_user)
        else
            render :edit
        end
    end

    def destroy
        set_review
        @review.delete
        redirect_to user_reviews_path(current_user)
    end

    def newest_reviews
        @reviews = Review.newest_reviews
    end

    private 

    def review_params
        params.require(:review).permit(:rating, :content, :anime_id)
    end

    def set_review
        @review = Review.find_by_id(params[:id])
        redirect_to reviews_path if !@review || @review.user != current_user
    end

    def check_user
        params[:user_id] && @user = User.find_by_id(params[:user_id])
    end

    def check_anime
        params[:anime_id] && @anime = Anime.find_by_id(params[:anime_id])
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def welcome
        
    end
###render login view
    def new
        render :login 
    end
###login to show page 
    def create 
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id 
            redirect_to user_path(user)
        else
            redirect_to '/login'
        end
    end
###logout
    def destroy
        session.clear
        redirect_to '/'
    end

    def omniauth
        @user = User.find_or_create_by(username: auth["info"]["name"]) do |user|
            user.password = SecureRandom.hex(12)
        end
        if @user && @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user) 
        else
            redirect_to '/'
        end

    end

    private
    
    def auth 
        request.env['omniauth.auth']
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
###render signup
    def new
        @user = User.new 
    end
###signup and redirect
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else
            render :new 
        end
    end

    def show 
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user 
    end

    
    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def new_display_header
        if @review.anime
            "Make a review for #{@review.anime.title}"
        else
            "New Review!"
        end
    end

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animes/index.html.erb
<h1> Click the title to add or view reviews!</h1> 
<h3>If you do not see your title then <%= link_to 'add an Anime', new_anime_path %> to the list</h3>
<% @animes.each do |a| %>
    <li> <%= link_to a.title, anime_reviews_path(a) %> </li>
    <% end %>
    

app/views/animes/new.html.erb
<h1>Add a new anime to the available titles to review!</h1>

<%= render partial: "layouts/errors", locals: {object: @anime} %>

<%= form_for(@anime) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
    <% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YouReviewAnime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div> 
      <% if logged_in?%>
      <%= link_to 'All Anime', animes_path %> |
      <%= link_to 'All Reviews', reviews_path %> |
      <%= link_to 'Add a Review', new_review_path %> |
      <%= link_to 'My Reviews', user_reviews_path(current_user) %> |
      <%= link_to 'Home Page', user_path(current_user) %> |
      <%= link_to 'Log Out', logout_path, method: "delete" %>
      <% end %>

  <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1> Edit your review for <%= @review.anime.title %>!</h1>

<%= render partial: "layouts/errors", locals: {object: @review} %>

<%= form_for(@review) do |f| %>

    <%= f.label :rating %>
    <%= f.number_field :rating, :min => 1, :max => 10 %>

    <%= f.label :content %> 
    <%= f.text_area :content, :cols => 30, :rows => 8 %> 
    
    <%= f.submit %> 

<% end %>

app/views/reviews/index.html.erb
<% if @anime %>
    <h1>Reviews for <%= @anime.title%> </h1>
    <%= link_to 'click here to review this anime!', new_anime_review_path %>
<% elsif @user %>
    <h1> Your Reviews! </h1>
<% else %>
    <h1>All Reviews</h1>
<% end %>

<ul>
<% if @anime %>
    <% if @reviews.none? %>
        <h3> No reviews yet, be the first! </h3>
    <% end %>
    <% @reviews.each do |r| %>
        <li><%= r.user.username %> |
        <%= r.rating %> |
        <%= r.content %> </l1>
        <br>
       <% end %>
<% elsif @user %>
    <h4> Click the title to go to that anime's review page. </h4>
    <% @reviews.each do |r| %>
        <li> 
        <%= link_to r.anime.title, anime_reviews_path(r.anime_id) %> |
        <%= r.rating %> |
        <%= r.content %> 
        <%= link_to 'edit', edit_review_path(r) %> |
        <%= link_to 'delete', review_path(r), method: "delete" %> 
        </li>
    <% end %>
<% else %> 
    <% @reviews.each do |r| %>
        <li> <%= r.user.username%> rated <%= link_to r.anime.title, anime_reviews_path(r.anime_id) %> a <%= r.rating %> 
        Click the title to find out why!
        </li>
    <% end %>
<% end %>
    </ul>

app/views/reviews/new.html.erb
<h1><%= new_display_header %></h1>

<%= render partial: "layouts/errors", locals: {object: @review} %>

<%= form_for([@review.anime,@review]) do |f| %>
    <% if !@review.anime %>
        <%= f.label :anime %>
        <%= f.collection_select :anime_id, Anime.all, :id, :title %> 
    <% else %> 
        <%= f.hidden_field :anime_id %>
    <% end %> 

    <%= f.label :rating %>
    <%= f.number_field :rating, :min => 1, :max => 10 %>
    <%= f.label :content %> 
    <%= f.text_area :content, :cols => 30, :rows => 8 %> 
    <%= f.submit %> 
<% end %>

app/views/reviews/newest_reviews.html.erb
<h2> As of today the 5 newest reviews are... </h2>

<%  @reviews.each do |r|  %>
<%= r.anime.title %> by
<%= r.user.username %>
<br>
<% end %> 

app/views/users/new.html.erb
<h1>Signup for an account below!</h1>

<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <%=f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome to You-Review-Anime <%=@user.username %>! </h1>We here behind the screen hope you enjoy your stay, but please refrain from spoiling anime in your reviews. 
If deemed guilty on multiple occasions you will be banned. You wouldn't want plots spoiled for you right? Thank you for your coorperation!

<h3> Click <%= link_to 'here', reviews_newest_reviews_path %> to view the 5 recently reviewed anime </h3>